import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Mock Javipas - AI Generated",
  description: "Un blog simulado con IA.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="antialiased">
      <body className="min-h-screen bg-white dark:bg-zinc-950 text-zinc-900 dark:text-zinc-50 selection:bg-zinc-100 dark:selection:bg-zinc-800">
        <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col min-h-screen">
          
          <header className="py-12 md:py-16">
            <nav className="flex items-center justify-between">
              <Link href="/" className="font-bold text-2xl tracking-tight hover:opacity-80 transition-opacity">
                AIBlog.
              </Link>
              <div className="text-sm font-medium text-zinc-500 dark:text-zinc-400">
                Generated by Aphra
              </div>
            </nav>
          </header>

          <main className="flex-1">
            {children}
          </main>

          <footer className="py-10 mt-12 border-t border-zinc-100 dark:border-zinc-900 flex justify-between items-center text-sm text-zinc-500">
            <span>© {new Date().getFullYear()} AI Blogger.</span>
            <span>Estilo de Javipas</span>
          </footer>

        </div>
      </body>
    </html>
  );
}
